# Generated by Django 4.2 on 2024-12-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, verbose_name='日期')),
                ('title', models.CharField(max_length=50, verbose_name='项目')),
                ('shuliang', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True, verbose_name='数量')),
                ('danjia', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True, verbose_name='单价')),
                ('hanshuijine', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='含税金额')),
                ('shuie', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='税额')),
            ],
            options={
                'verbose_name_plural': '采购项目',
            },
        ),
        migrations.CreateModel(
            name='SalesProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, verbose_name='日期')),
                ('title', models.CharField(max_length=50, verbose_name='项目')),
                ('shuliang', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True, verbose_name='数量')),
                ('danjia', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True, verbose_name='单价')),
                ('hanshuijine', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='含税金额')),
                ('shuie', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='税额')),
            ],
            options={
                'verbose_name_plural': '销售项目',
            },
        ),
    ]
