# Generated by Django 4.2 on 2024-12-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxdisplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaipiaoriqi', models.CharField(max_length=50, verbose_name='开票日期')),
                ('title', models.CharField(max_length=50, verbose_name='数电票号码')),
                ('jine', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True, verbose_name='金额')),
                ('piaomianshuie', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True, verbose_name='票面税额')),
                ('xiaoshoufangmingcheng', models.CharField(max_length=50, verbose_name='销售方名称')),
            ],
            options={
                'verbose_name_plural': '进项发票',
            },
        ),
        migrations.CreateModel(
            name='OutputInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaipiaoriqi', models.CharField(max_length=50, verbose_name='开票日期')),
                ('title', models.CharField(max_length=50, verbose_name='数电票号码')),
                ('jine', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True, verbose_name='金额')),
                ('piaomianshuie', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True, verbose_name='票面税额')),
                ('goumaifangmingcheng', models.CharField(max_length=50, verbose_name='购买方名称')),
            ],
            options={
                'verbose_name_plural': '销项发票',
            },
        ),
    ]
