# Generated by Django 4.2 on 2024-12-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxdisplay', '0003_alter_inputinvoice_jine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputinvoice',
            name='date',
            field=models.CharField(default=2013, max_length=50, verbose_name='所属期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outputinvoice',
            name='date',
            field=models.CharField(default=2013, max_length=50, verbose_name='所属期'),
            preserve_default=False,
        ),
    ]
