# Generated by Django 4.2 on 2024-12-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='菜单名')),
                ('url', models.CharField(max_length=64, verbose_name='含正则URL路径')),
            ],
            options={
                'verbose_name_plural': '菜单表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='角色名')),
                ('menus', models.ManyToManyField(blank=True, to='users.menu', verbose_name='菜单')),
            ],
            options={
                'verbose_name_plural': '菜单表',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='menus',
            field=models.ManyToManyField(blank=True, to='users.menu', verbose_name='菜单'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='users.role', verbose_name='角色'),
        ),
    ]
