# Generated by Django 4.2 on 2024-12-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_menu_role_user_menus_user_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '角色表'},
        ),
        migrations.AddField(
            model_name='menu',
            name='titlecode',
            field=models.CharField(default=1, help_text='例如:01-01', max_length=50, verbose_name='菜单编码'),
            preserve_default=False,
        ),
    ]
